version: '3.8'

services:
  knowledge-hub:
    image: ghcr.io/bebang-enterprise-inc/bei-knowledge-hub:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.knowledge-hub.rule=Host(`knowledge.bebang.ph`)"
        - "traefik.http.services.knowledge-hub.loadbalancer.server.port=8000"
    environment:
      # Secrets via AWS Secrets Manager or Doppler
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}
      - API_KEY=${KNOWLEDGE_HUB_API_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=info
    networks:
      - swarm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  swarm-network:
    external: true
